---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag
  namespace: wallabag
spec:
  instances: 2
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn-custom
      volumeMode: Filesystem
