---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  labels:
    app: prowlarr
spec:
  destination:
    namespace: prowlarr
    server: https://kubernetes.default.svc
  project: media
  sources:
  - chart: prowlarr
    repoURL: https://k8s-home-lab.github.io/helm-charts/
    targetRevision: 5.1.2
    helm:
      valueFiles:
        - $values/src/kubernetes/apps/media/prowlarr/values.yml
  - repoURL: 'https://github.com/TheLionsRain/homelab.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
