---
podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568

persistence:
  config:
    enabled: true
    size: 100m
    storageClass: longhorn-custom
    mountPath: /config

env:
  TZ: "Europe/Brussels"
