---
- name: Create External Secrets manifest directory
  ansible.builtin.file:
    path: /opt/kubernetes/manifests/external-secrets
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
  become: true

- name: Add external-secrets Helm repository
  kubernetes.core.helm_repository:
    name: external-secrets
    repo_url: "https://charts.external-secrets.io"

- name: Deploy external-secrets Helm chart
  kubernetes.core.helm:
    name: external-secrets
    chart_ref: external-secrets/external-secrets
    release_namespace: external-secrets
    create_namespace: true

- name: Wait for external-secrets to be ready
  ansible.builtin.wait_for:
    timeout: 60
  delegate_to: localhost
  when: not cilium_installed

- name: Template SecretStore Secret manifest
  ansible.builtin.template:
    src: external-secrets/secret-store-secret.yml.jinja2
    dest: /opt/kubernetes/manifests/external-secrets/secret-store-secret.yml
    mode: '0644'

- name: Apply SecretStore Secret manifest
  kubernetes.core.k8s:
    src: /opt/kubernetes/manifests/external-secrets/secret-store-secret.yml
    state: present

- name: Template ClusterSecretStore manifest
  ansible.builtin.template:
    src: external-secrets/cluster-secret-store.yml.jinja2
    dest: /opt/kubernetes/manifests/external-secrets/cluster-secret-store.yml
    mode: '0644'

- name: Apply ClusterSecretStore manifest
  kubernetes.core.k8s:
    src: /opt/kubernetes/manifests/external-secrets/cluster-secret-store.yml
    state: present

- name: Copy Cloudflare API token Secret manifest
  ansible.builtin.copy:
    src: files/external-secrets/cloudflare-api-token-secret.yml
    dest: /opt/kubernetes/manifests/external-secrets/cloudflare-api-external-secret.yml
    mode: '0644'

- name: Apply Cloudflare API ClusterExternalSecret manifest
  kubernetes.core.k8s:
    src: /opt/kubernetes/manifests/external-secrets/cloudflare-api-external-secret.yml
    state: present
