---
- name: Download GitHub CLI GPG key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli.gpg
    mode: '0644'
  become: true

- name: Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch_result
  changed_when: false

- name: Set dpkg architecture fact
  ansible.builtin.set_fact:
    dpkg_architecture: "{{ dpkg_arch_result.stdout }}"

- name: Add GitHub CLI apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_architecture }} signed-by=/etc/apt/keyrings/githubcli.gpg] https://cli.github.com/packages stable main"
    filename: githubcli
    state: present
  become: true

- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install GitHub CLI
  ansible.builtin.apt:
    name: gh
    state: present
  become: true
