---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.valhallahub.nl
  dex.config: |
    connectors:
    - config:
        issuer: https://authentik.valhallahub.nl/application/o/argocd/
        clientID: L9nKlXRLHY2n1ECAXcFRtZqGW79JRAD7TJg7bZ7Z
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik
