---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-patch
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  refreshInterval: "1h"
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      data:
        dex.authentik.clientSecret: "{{ .clientsecret }}"
  data:
  - secretKey: clientsecret
    remoteRef:
      key: argocd-authentik-client-secret
