---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  sources:
  - chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
  - repoURL: 'https://github.com/TheLionsRain/homelab.git'
    path: src/kubernetes/core/longhorn/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true