---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-client-secret
  namespace: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  refreshInterval: "1h"
  target:
    name: authentik-client-secret
    creationPolicy: Owner
    template:
      data:
        OIDC_CLIENT_SECRET: "{{ .clientsecret }}"
  data:
  - secretKey: clientsecret
    remoteRef:
      key: freshrss-authentik-client-secret
