---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-crypto-key
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  refreshInterval: "1h"
  target:
    name: authentik-crypto-key
    creationPolicy: Owner
    template:
      data:
        authentik-crypto-key: "{{ .authentikcryptokey }}"
  data:
  - secretKey: authentikcryptokey
    remoteRef:
      key: authentik-crypto-key
