---
- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Install Dependencies
  ansible.builtin.include_tasks: install-dependencies.yml

- name: Install Docker
  ansible.builtin.include_tasks: install-docker.yml
