---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: general
  namespace: argocd
spec:
  description: An ArgoCD project for the general components.
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
