---
replicas: 2

serviceAccount:
  name: vaultwarden

storage:
  data:
    size: 2Gi
    name: vaultwarden-data
    class: longhorn-custom
    path: /data
    keepPvc: true
    accessMode: ReadWriteOnce

  attachments:
    size: 5Gi
    name: vaultwarden-files
    class: longhorn-custom
    path: /files
    keepPvc: true
    accessMode: ReadWriteOnce

database:
  type: postgresql
  existingSecret: vaultwarden-app
  existingSecretKey: uri

domain: vaultwarden.valhallahub.nl