envFrom:
- configMapRef:
    name: freshrss
- secretRef:
    name: authentik-client-secret

persistence:
  config:
    enabled: true
    size: 100m
    storageClass: longhorn-custom

env.TZ: "Belgium/Brussels"