---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-azblob
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  refreshInterval: "1h"
  target:
    name: longhorn-azblob
    creationPolicy: Owner
    template:
      data:
        AZBLOB_ACCOUNT_NAME: "{{ .longhornazblobaccountname | toString }}"
        AZBLOB_ACCOUNT_KEY: "{{ .longhornazblobaccountkey | toString }}"
  data:
  - secretKey: longhornazblobaccountname
    remoteRef:
      key: backup-storage-name
  - secretKey: longhornazblobaccountkey
    remoteRef:
      key: backup-storage-key
