---
all:
  hosts:
    muspelheim-001:
      ansible_host: 10.0.4.5
      ansible_ssh_private_key_file: ~/.ssh/muspelheim
      ansible_user: michiel
    muspelheim-002:
      ansible_host: 10.0.4.6
      ansible_ssh_private_key_file: ~/.ssh/muspelheim
      ansible_user: michiel
    muspelheim-003:
      ansible_host: 10.0.4.7
      ansible_ssh_private_key_file: ~/.ssh/muspelheim
      ansible_user: michiel

  children:
    ubuntu:
      hosts:
        muspelheim-001:
        muspelheim-002:
        muspelheim-003:

    muspelheim_cluster:
      hosts:
        muspelheim-001:
        muspelheim-002:
        muspelheim-003:

    muspelheim_leader:
      hosts:
        muspelheim-001:

    muspelheim_managers:
      hosts:
        muspelheim-002:
        muspelheim-003:
