---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-api-key-clustersecret
spec:
  externalSecretName: cloudflare-api-key-secret
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - cert-manager
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: azure-key-vault
    refreshInterval: "1h"
    target:
      name: cloudflare-api-key
      creationPolicy: Owner
      template:
        data:
          api-token: "{{ .cloudflareapitoken }}"
    data:
    - secretKey: cloudflareapitoken
      remoteRef:
        key: cloudflare-api-token
