---
name: CD - Kubernetes Initialize

on:
  push:
    branches:
    - main
    paths:
      - src/ansible/inventories/helheim.yml
      - src/ansible/playbooks/kubernetes_initialize.yml
      - src/ansible/roles/kubernetes_leader/**
  workflow_dispatch:

jobs:
  initialize-helheim-kubernetes:
    name: Initialize Kubernetes Cluster - Helheim
    uses: TheLionsRain/reusable-workflows/.github/workflows/deploy-ansible.yml@deploy-ansible-v1.0.1
    with:
      RUNS_ON: self-hosted
      ENVIRONMENT: helheim
      SSH_KEY_PATH: ~/.ssh/helheim
      FILES_TO_TOKENIZE: '["src/ansible/inventories/group_vars/helheim_cluster.yml"]'
      INVENTORY: src/ansible/inventories/helheim.yml
      PLAYBOOK_PATH: src/ansible/playbooks
      PLAYBOOK: kubernetes_initialize.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      TOKENS: '{
          "EXTERNAL_SECRETS_CLIENT_SECRET": "${{ secrets.EXTERNAL_SECRETS_CLIENT_SECRET }}",
          "ACCESS_TOKEN": "${{ secrets.ACCESS_TOKEN }}"
        }'
