---
name: CD - Swarm Worker

on:
  push:
    branches:
    - main
    paths:
    - src/ansible/inventories/muspelheim.yml
    - src/ansible/playbooks/swarm_join.worker.yml
    - src/ansible/roles/swarm_worker/**
  workflow_dispatch:

jobs:
  deploy-muspelheim-swarm-workers:
    name: Deploy Swarm Worker
    uses: TheLionsRain/reusable-workflows/.github/workflows/deploy-ansible.yml@deploy-ansible-v1.0.1
    with:
      RUNS_ON: self-hosted
      ENVIRONMENT: muspelheim
      SSH_KEY_PATH: ~/.ssh/muspelheim
      FILES_TO_TOKENIZE: '["src/ansible/roles/swarm_worker/defaults/main.yml"]'
      INVENTORY: src/ansible/inventories/muspelheim.yml
      PLAYBOOK_PATH: src/ansible/playbooks
      PLAYBOOK: swarm_join.worker.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      TOKENS: '{
          "SWARM_WORKER_TOKEN": "${{ secrets.SWARM_WORKER_TOKEN }}"
        }'