---
name: CI - Terraform

on:
  pull_request:
    branches:
    - main
    paths:
    - src/terraform/**

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan-terraform:
    name: Validate Terraform
    uses: TheLionsRain/reusable-workflows/.github/workflows/plan-terraform.yml@plan-terraform-v1.0.0
    with:
      ENVIRONMENT: helheim
      TERRAFORM_WORKING_DIRECTORY: src/terraform
      TERRAFORM_BACKEND: src/terraform/tfbackends/helheim.tfbackend
      TERRAFORM_VARFILE: src/terraform/tfvars/helheim.tfvars
      TERRAFORM_PLAN_NAME: helheim.tfplan
      FILES_TO_TOKENIZE: src/terraform/tfvars/helheim.tfvars
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
      TOKENS: '{
          CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}",
        }'